checks:
  - check: check-message
    regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'
    error: "The commit message should have a conventional commit format. For more details please refer to https://www.conventionalcommits.org"
    suggest: 'git commit --amend'
