name: "Install dependencies"
description: "Installs dependencies for workflow"
runs:
  using: "composite"
  steps:
    - name: Install just
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh \
          | sudo bash -s -- --to /usr/bin
