[package]
name = "ixa_example_basic_infection"
version = "0.1.0"
repository.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
authors.workspace = true

publish = false

[dependencies]
ixa = { path = "../../../ixa" }
ixa-derive = { path = "../../ixa-derive" }

csv.workspace = true
serde.workspace = true
rand.workspace = true
rand_distr.workspace = true
paste.workspace = true

[lints]
workspace = true

[[bin]]
name = "basic_infection"
path = "main.rs"
