name: Setup environment
description: Install cargo binstall and mise environment
runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v3

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo-install/
          ~/.rustup/toolchains/
          docs/book/book/
        key: cargo-${{ hashFiles('Cargo.toml') }}
