#[cfg(test)]
mod tests {
    use std::hash::{Hash, Hasher};

    use ixa::prelude::*;
    use ixa::HashSet;
    use serde::{Deserialize, Serialize};

    define_entity!(Person);

    // Test entity property / derived / multi-property macros
    define_property!(struct TestPropU32(u32), Person);
    define_property!(struct TestPropU32b(u32), Person);
    define_property!(
        struct TestPropDefault(u32),
        Person,
        default_const = TestPropDefault(7u32)
    );
    define_property!(
        struct TestPropOpt(Option<u8>),
        Person,
        default_const = TestPropOpt(None)
    );

    // Tests of the `impl_eq_hash = ...` mechanism
    // Both `PartialEq` / `Eq` and `Hash` are generated by the macro
    define_property!(struct TestFloatBoth(f64), Person, impl_eq_hash = both, default_const = TestFloatBoth(0.0));
    // Only `PartialEq` / `Eq` is generated by the macro
    define_property!(struct TestFloatEq(f64), Person, impl_eq_hash = Eq, default_const = TestFloatEq(0.0));
    impl Hash for TestFloatEq {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    // Only `Hash` is generated by the macro
    define_property!(struct TestFloatHash(f64), Person, impl_eq_hash = Hash, default_const = TestFloatHash(0.0));
    impl PartialEq for TestFloatHash {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for TestFloatHash {}
    // Neither `PartialEq` / `Eq` nor `Hash` are generated by the macro
    define_property!(struct TestFloatNeither(f64), Person, impl_eq_hash = neither, default_const = TestFloatNeither(0.0));
    impl Hash for TestFloatNeither {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    impl PartialEq for TestFloatNeither {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for TestFloatNeither {}

    // Analogous tests of the `impl_eq_hash = ...` mechanism for `define_derived_property!`
    // Both `PartialEq` / `Eq` and `Hash` are generated by the macro
    define_derived_property!(
        struct DerivedFloatBoth(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatBoth(v.0 as f64),
        impl_eq_hash = both
    );
    // Only `PartialEq` / `Eq` is generated by the macro
    define_derived_property!(
        struct DerivedFloatEq(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatEq(v.0 as f64),
        impl_eq_hash = Eq
    );
    impl Hash for DerivedFloatEq {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    // Only `Hash` is generated by the macro
    define_derived_property!(
        struct DerivedFloatHash(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatHash(v.0 as f64),
        impl_eq_hash = Hash
    );
    impl PartialEq for DerivedFloatHash {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for DerivedFloatHash {}
    // Neither `PartialEq` / `Eq` nor `Hash` are generated by the macro
    define_derived_property!(
        struct DerivedFloatNeither(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatNeither(v.0 as f64),
        impl_eq_hash = neither
    );
    impl Hash for DerivedFloatNeither {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    impl PartialEq for DerivedFloatNeither {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for DerivedFloatNeither {}

    // Test derived property macro
    define_derived_property!(struct DerivedProp(pub u32), Person, [TestPropU32], |v| {
        let v: TestPropU32 = v;
        DerivedProp(v.0 + 1)
    });

    type MultiProp = (TestPropU32, TestPropU32b);
    define_multi_property!((TestPropU32, TestPropU32b), Person);

    // Test global property macro
    define_global_property!(TestGlobal, u32);

    // Test edge type macro
    define_edge_type!(struct TestEdge, Person);

    // Test report macro
    #[derive(Serialize, Deserialize)]
    struct SampleR {
        x: u32,
    }
    define_report!(SampleR);

    // Test data plugin macro (simple container)
    define_data_plugin!(TestDataPlugin, Vec<u8>, vec![1u8, 2u8]);

    // Test rng macro
    define_rng!(TestRngId);

    #[test]
    fn compile_and_run_macros() {
        let mut ctx = Context::new();

        // Check global property registration works (add and set)
        ctx.set_global_property_value(TestGlobal, 42u32).unwrap();
        let v = *ctx.get_global_property_value(TestGlobal).unwrap();
        assert_eq!(v, 42u32);

        // Entity properties: add a Person with TestPropU32
        let pid: EntityId<Person> = ctx
            .add_entity(with!(
                Person,
                TestPropU32(10u32),
                TestPropU32b(20u32),
                TestPropOpt(Some(3u8)),
            ))
            .unwrap();
        let val: TestPropU32 = ctx.get_property(pid);
        assert_eq!(val.0, 10u32);
        // Verify default property value is set for TestPropDefault
        let default_val: TestPropDefault = ctx.get_property(pid);
        assert_eq!(default_val.0, 7u32);

        // Derived property should compute from TestPropU32
        let d: DerivedProp = ctx.get_property(pid);
        assert_eq!(d.0, 11u32);

        // Derived property `impl_eq_hash = ...` variants should all compile and behave as hashable keys.
        let mut derived_float_both = HashSet::default();
        derived_float_both.insert(ctx.get_property::<_, DerivedFloatBoth>(pid));
        assert!(derived_float_both.contains(&DerivedFloatBoth(10.0)));

        let mut derived_float_eq = HashSet::default();
        derived_float_eq.insert(ctx.get_property::<_, DerivedFloatEq>(pid));
        assert!(derived_float_eq.contains(&DerivedFloatEq(10.0)));

        let mut derived_float_hash = HashSet::default();
        derived_float_hash.insert(ctx.get_property::<_, DerivedFloatHash>(pid));
        assert!(derived_float_hash.contains(&DerivedFloatHash(10.0)));

        let mut derived_float_neither = HashSet::default();
        derived_float_neither.insert(ctx.get_property::<_, DerivedFloatNeither>(pid));
        assert!(derived_float_neither.contains(&DerivedFloatNeither(10.0)));

        // Multi-property - basic sanity (canonical value types)
        let multi = <MultiProp as Property<Person>>::make_canonical((
            TestPropU32(10u32),
            TestPropU32b(20u32),
        ));
        let disp = <MultiProp as Property<Person>>::get_display(&multi);
        assert!(disp.contains("10"));

        // Edge type (entity-based network): create two people and add an edge of type TestEdge
        let p1 = ctx
            .add_entity(with!(Person, TestPropU32(1u32), TestPropU32b(1u32)))
            .unwrap();
        let p2 = ctx
            .add_entity(with!(Person, TestPropU32(2u32), TestPropU32b(2u32)))
            .unwrap();
        ctx.add_edge::<Person, TestEdge>(p1, p2, 1.0, TestEdge)
            .unwrap();
        let e = ctx.get_edge::<Person, TestEdge>(p1, p2).unwrap();
        assert_eq!(e.weight, 1.0);
        // Now remove the edge and ensure it's gone
        ctx.remove_edge::<Person, TestEdge>(p1, p2);
        assert!(ctx.get_edge::<Person, TestEdge>(p1, p2).is_none());

        // Data plugin access
        let data: &Vec<u8> = ctx.get_data(TestDataPlugin);
        assert_eq!(data.len(), 2);

        // RNG macro: initialize random subsystem and sample to ensure macro-generated types work
        ctx.init_random(42);
        let _ = ctx.sample(TestRngId, |_rng| 1u32);

        // Report: write into a temp directory so existing files don't interfere
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().to_path_buf();
        let opts = ctx.report_options();
        opts.directory(path.clone());
        opts.overwrite(true);

        ctx.add_report::<SampleR>("sample_report").unwrap();
        ctx.send_report(SampleR { x: 5 });

        // Flush the writer so data is on disk, then verify CSV file exists and contains the sample row
        let mut writer = ctx.get_writer(std::any::TypeId::of::<SampleR>());
        writer.flush().unwrap();

        let file_path = path.join("sample_report.csv");
        let contents = std::fs::read_to_string(&file_path).unwrap();
        assert!(!contents.is_empty());
        assert!(contents.contains("5"));

        // assert_almost_eq macro usage
        let a = 1.0f64;
        let b = 1.0f64 + 1e-12;
        ixa::assert_almost_eq!(a, b, 1e-10);
    }
}
