#[cfg(test)]
mod tests {
    use std::cell::RefCell;
    use std::hash::{Hash, Hasher};
    use std::rc::Rc;

    use ixa::prelude::*;
    use ixa::HashSet;
    use serde::{Deserialize, Serialize};

    define_entity!(Person);

    // Test entity property / derived / multi-property macros
    define_property!(struct TestPropU32(u32), Person);
    define_property!(struct TestPropU32b(u32), Person);
    define_property!(struct MacroAge(u8), Person, default_const = MacroAge(0));
    define_property!(
        struct MacroHighRisk(bool),
        Person,
        default_const = MacroHighRisk(false)
    );
    define_property!(
        enum MacroInfectionStatus {
            Susceptible,
            Infected,
            Recovered,
        },
        Person,
        default_const = MacroInfectionStatus::Susceptible
    );
    define_property!(
        struct TestPropDefault(u32),
        Person,
        default_const = TestPropDefault(7u32)
    );
    define_property!(
        struct TestPropOpt(Option<u8>),
        Person,
        default_const = TestPropOpt(None)
    );

    // Tests of the `impl_eq_hash = ...` mechanism
    // Both `PartialEq` / `Eq` and `Hash` are generated by the macro
    define_property!(struct TestFloatBoth(f64), Person, impl_eq_hash = both, default_const = TestFloatBoth(0.0));
    // Only `PartialEq` / `Eq` is generated by the macro
    define_property!(struct TestFloatEq(f64), Person, impl_eq_hash = Eq, default_const = TestFloatEq(0.0));
    impl Hash for TestFloatEq {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    // Only `Hash` is generated by the macro
    define_property!(struct TestFloatHash(f64), Person, impl_eq_hash = Hash, default_const = TestFloatHash(0.0));
    impl PartialEq for TestFloatHash {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for TestFloatHash {}
    // Neither `PartialEq` / `Eq` nor `Hash` are generated by the macro
    define_property!(struct TestFloatNeither(f64), Person, impl_eq_hash = neither, default_const = TestFloatNeither(0.0));
    impl Hash for TestFloatNeither {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    impl PartialEq for TestFloatNeither {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for TestFloatNeither {}

    // Tests of standalone generated equality / hash macros for manually declared properties.
    #[derive(
        Debug, Clone, Copy, Serialize, Deserialize, ixa::rkyv::Archive, ixa::rkyv::Serialize,
    )]
    #[rkyv(crate = ixa::rkyv)]
    struct ManualFloatBoth(f64);
    impl_property_eq_hash!(ManualFloatBoth);
    impl_property!(
        ManualFloatBoth,
        Person,
        default_const = ManualFloatBoth(0.0)
    );

    #[derive(
        Debug, Clone, Copy, Serialize, Deserialize, ixa::rkyv::Archive, ixa::rkyv::Serialize,
    )]
    #[rkyv(crate = ixa::rkyv)]
    struct ManualFloatEq(f64);
    impl_property_eq!(ManualFloatEq);
    impl Hash for ManualFloatEq {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    impl_property!(ManualFloatEq, Person, default_const = ManualFloatEq(0.0));

    #[derive(
        Debug, Clone, Copy, Serialize, Deserialize, ixa::rkyv::Archive, ixa::rkyv::Serialize,
    )]
    #[rkyv(crate = ixa::rkyv)]
    struct ManualFloatHash(f64);
    impl PartialEq for ManualFloatHash {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for ManualFloatHash {}
    impl_property_hash!(ManualFloatHash);
    impl_property!(
        ManualFloatHash,
        Person,
        default_const = ManualFloatHash(0.0)
    );

    // Analogous tests of the `impl_eq_hash = ...` mechanism for `define_derived_property!`
    // Both `PartialEq` / `Eq` and `Hash` are generated by the macro
    define_derived_property!(
        struct DerivedFloatBoth(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatBoth(v.0 as f64),
        impl_eq_hash = both
    );
    // Only `PartialEq` / `Eq` is generated by the macro
    define_derived_property!(
        struct DerivedFloatEq(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatEq(v.0 as f64),
        impl_eq_hash = Eq
    );
    impl Hash for DerivedFloatEq {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    // Only `Hash` is generated by the macro
    define_derived_property!(
        struct DerivedFloatHash(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatHash(v.0 as f64),
        impl_eq_hash = Hash
    );
    impl PartialEq for DerivedFloatHash {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for DerivedFloatHash {}
    // Neither `PartialEq` / `Eq` nor `Hash` are generated by the macro
    define_derived_property!(
        struct DerivedFloatNeither(f64),
        Person,
        [TestPropU32],
        |v| DerivedFloatNeither(v.0 as f64),
        impl_eq_hash = neither
    );
    impl Hash for DerivedFloatNeither {
        fn hash<H: Hasher>(&self, state: &mut H) {
            state.write_u64(self.0.to_bits());
        }
    }
    impl PartialEq for DerivedFloatNeither {
        fn eq(&self, other: &Self) -> bool {
            self.0.to_bits() == other.0.to_bits()
        }
    }
    impl Eq for DerivedFloatNeither {}

    #[derive(
        Debug, Clone, Copy, Serialize, Deserialize, ixa::rkyv::Archive, ixa::rkyv::Serialize,
    )]
    #[rkyv(crate = ixa::rkyv)]
    struct ManualDerivedFloat(f64);
    impl_property_eq_hash!(ManualDerivedFloat);
    ixa::impl_derived_property!(ManualDerivedFloat, Person, [TestPropU32], |v| {
        ManualDerivedFloat(v.0 as f64)
    });

    // Test derived property macro
    define_derived_property!(struct DerivedProp(pub u32), Person, [TestPropU32], |v| {
        let v: TestPropU32 = v;
        DerivedProp(v.0 + 1)
    });

    type MultiProp = (TestPropU32, TestPropU32b);
    define_multi_property!(Person, (TestPropU32, TestPropU32b));

    // Test global property macro
    define_global_property!(TestGlobal, u32);

    // Test edge type macro
    define_edge_type!(struct TestEdge, Person);

    // Test report macro
    #[derive(Serialize, Deserialize)]
    struct SampleR {
        x: u32,
    }
    define_report!(SampleR);

    // Test data plugin macro (simple container)
    define_data_plugin!(TestDataPlugin, Vec<u8>, vec![1u8, 2u8]);

    // Test rng macro
    define_rng!(TestRngId);

    fn as_context(context: &mut Context) -> &mut Context {
        context
    }

    fn macro_named_value_change_handler<C>(_context: &mut Context, _counter: &mut C) {}

    fn record_sum(
        context: &mut Context,
        records: Rc<RefCell<Vec<(f64, u32)>>>,
        arg1: u32,
        arg2: u32,
        arg3: u32,
    ) {
        records
            .borrow_mut()
            .push((context.get_current_time(), arg1 + arg2 + arg3));
    }

    fn record_current_time(context: &mut Context, records: Rc<RefCell<Vec<f64>>>) {
        records.borrow_mut().push(context.get_current_time());
    }

    fn passthrough_context(context: &mut Context) -> &mut Context {
        context
    }

    #[test]
    fn compile_and_run_macros() {
        let mut ctx = Context::new();

        // Check global property registration works (add and set)
        ctx.set_global_property_value(TestGlobal, 42u32).unwrap();
        let v = *ctx.get_global_property_value(TestGlobal).unwrap();
        assert_eq!(v, 42u32);

        // Entity properties: add a Person with TestPropU32
        let pid: EntityId<Person> = ctx
            .add_entity(with!(
                Person,
                TestPropU32(10u32),
                TestPropU32b(20u32),
                TestPropOpt(Some(3u8)),
            ))
            .unwrap();
        let val: TestPropU32 = ctx.get_property(pid);
        assert_eq!(val.0, 10u32);
        // Verify default property value is set for TestPropDefault
        let default_val: TestPropDefault = ctx.get_property(pid);
        assert_eq!(default_val.0, 7u32);

        // Standalone generated equality / hash macros should support manually declared property
        // types that are then registered with `impl_property!`.
        let mut manual_float_both = HashSet::default();
        manual_float_both.insert(ctx.get_property::<_, ManualFloatBoth>(pid));
        assert!(manual_float_both.contains(&ManualFloatBoth(0.0)));

        let mut manual_float_eq = HashSet::default();
        manual_float_eq.insert(ctx.get_property::<_, ManualFloatEq>(pid));
        assert!(manual_float_eq.contains(&ManualFloatEq(0.0)));

        let mut manual_float_hash = HashSet::default();
        manual_float_hash.insert(ctx.get_property::<_, ManualFloatHash>(pid));
        assert!(manual_float_hash.contains(&ManualFloatHash(0.0)));

        // Derived property should compute from TestPropU32
        let d: DerivedProp = ctx.get_property(pid);
        assert_eq!(d.0, 11u32);

        let mut manual_derived_float = HashSet::default();
        manual_derived_float.insert(ctx.get_property::<_, ManualDerivedFloat>(pid));
        assert!(manual_derived_float.contains(&ManualDerivedFloat(10.0)));

        // Derived property `impl_eq_hash = ...` variants should all compile and behave as hashable keys.
        let mut derived_float_both = HashSet::default();
        derived_float_both.insert(ctx.get_property::<_, DerivedFloatBoth>(pid));
        assert!(derived_float_both.contains(&DerivedFloatBoth(10.0)));

        let mut derived_float_eq = HashSet::default();
        derived_float_eq.insert(ctx.get_property::<_, DerivedFloatEq>(pid));
        assert!(derived_float_eq.contains(&DerivedFloatEq(10.0)));

        let mut derived_float_hash = HashSet::default();
        derived_float_hash.insert(ctx.get_property::<_, DerivedFloatHash>(pid));
        assert!(derived_float_hash.contains(&DerivedFloatHash(10.0)));

        let mut derived_float_neither = HashSet::default();
        derived_float_neither.insert(ctx.get_property::<_, DerivedFloatNeither>(pid));
        assert!(derived_float_neither.contains(&DerivedFloatNeither(10.0)));

        // Multi-property - basic sanity.
        let multi = (TestPropU32(10u32), TestPropU32b(20u32));
        let disp = <MultiProp as Property<Person>>::get_display(&multi);
        assert!(disp.contains("10"));

        // Edge type (entity-based network): create two people and add an edge of type TestEdge
        let p1 = ctx
            .add_entity(with!(Person, TestPropU32(1u32), TestPropU32b(1u32)))
            .unwrap();
        let p2 = ctx
            .add_entity(with!(Person, TestPropU32(2u32), TestPropU32b(2u32)))
            .unwrap();
        ctx.add_edge::<Person, TestEdge>(p1, p2, 1.0, TestEdge)
            .unwrap();
        let e = ctx.get_edge::<Person, TestEdge>(p1, p2).unwrap();
        assert_eq!(e.weight, 1.0);
        // Now remove the edge and ensure it's gone
        assert!(ctx.remove_edge::<Person, TestEdge>(p1, p2).is_some());
        assert!(ctx.get_edge::<Person, TestEdge>(p1, p2).is_none());

        // Data plugin access
        let data: &Vec<u8> = ctx.get_data(TestDataPlugin);
        assert_eq!(data.len(), 2);

        // RNG macro: initialize random subsystem and sample to ensure macro-generated types work
        ctx.init_random(42);
        let _ = ctx.sample(TestRngId, |_rng| 1u32);

        // Report: write into a temp directory so existing files don't interfere
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().to_path_buf();
        let opts = ctx.report_options();
        opts.directory(path.clone());
        opts.overwrite(true);

        ctx.add_report::<SampleR>("sample_report").unwrap();
        ctx.send_report(SampleR { x: 5 });

        // Flush the writer so data is on disk, then verify CSV file exists and contains the sample row
        let mut writer = ctx.get_writer(std::any::TypeId::of::<SampleR>());
        writer.flush().unwrap();

        let file_path = path.join("sample_report.csv");
        let contents = std::fs::read_to_string(&file_path).unwrap();
        assert!(!contents.is_empty());
        assert!(contents.contains("5"));

        // assert_almost_eq macro usage
        let a = 1.0f64;
        let b = 1.0f64 + 1e-12;
        ixa::assert_almost_eq!(a, b, 1e-10);
    }

    #[test]
    fn track_periodic_value_change_counts_macro_forms() {
        let mut ctx = Context::new();

        let omitted_strata = Rc::new(RefCell::new(Vec::<usize>::new()));
        let empty_strata = Rc::new(RefCell::new(Vec::<usize>::new()));
        let singleton_strata = Rc::new(RefCell::new(Vec::<usize>::new()));
        let multiple_strata = Rc::new(RefCell::new(Vec::<usize>::new()));

        let omitted_strata_clone = omitted_strata.clone();
        track_periodic_value_change_counts!(
            as_context(&mut ctx),
            Person,
            MacroInfectionStatus,
            0.5 + 0.5,
            move |_context, counter| {
                omitted_strata_clone
                    .borrow_mut()
                    .push(counter.get_count((), MacroInfectionStatus::Infected));
            },
        );

        let empty_strata_clone = empty_strata.clone();
        track_periodic_value_change_counts!(
            ctx,
            Person,
            MacroInfectionStatus,
            [],
            1.0,
            move |_context, counter| {
                empty_strata_clone
                    .borrow_mut()
                    .push(counter.get_count((), MacroInfectionStatus::Infected));
            },
        );

        let singleton_strata_clone = singleton_strata.clone();
        track_periodic_value_change_counts!(
            ctx,
            Person,
            MacroInfectionStatus,
            [MacroAge],
            1.0,
            move |_context, counter| {
                singleton_strata_clone
                    .borrow_mut()
                    .push(counter.get_count((MacroAge(10),), MacroInfectionStatus::Infected));
            },
        );

        let multiple_strata_clone = multiple_strata.clone();
        track_periodic_value_change_counts!(
            ctx,
            Person,
            MacroInfectionStatus,
            [MacroAge, MacroHighRisk],
            1.0,
            move |_context, counter| {
                multiple_strata_clone.borrow_mut().push(counter.get_count(
                    (MacroAge(10), MacroHighRisk(true)),
                    MacroInfectionStatus::Infected,
                ));
            },
        );

        track_periodic_value_change_counts!(
            ctx,
            Person,
            MacroInfectionStatus,
            [],
            1.0,
            |_context, counter| {
                let _ = counter.get_count((), MacroInfectionStatus::Infected);
            },
        );

        track_periodic_value_change_counts!(
            ctx,
            Person,
            MacroInfectionStatus,
            [MacroAge],
            1.0,
            macro_named_value_change_handler,
        );

        let person = ctx
            .add_entity(with!(
                Person,
                TestPropU32(1),
                TestPropU32b(2),
                MacroAge(10),
                MacroHighRisk(true),
                MacroInfectionStatus::Susceptible,
            ))
            .unwrap();

        ctx.add_plan(0.5, move |context| {
            context.set_property(person, MacroInfectionStatus::Infected);
        });
        ctx.add_plan(1.1, Context::shutdown);

        ctx.execute();

        assert_eq!(*omitted_strata.borrow(), vec![0, 1]);
        assert_eq!(*empty_strata.borrow(), vec![0, 1]);
        assert_eq!(*singleton_strata.borrow(), vec![0, 1]);
        assert_eq!(*multiple_strata.borrow(), vec![0, 1]);
    }

    #[test]
    fn schedule_relative_accepts_function_name_with_arguments() {
        let mut context = Context::new();
        let records = Rc::new(RefCell::new(Vec::new()));
        let observed_records = records.clone();

        schedule_relative!(&mut context, 2.5, record_sum, records, 1, 2, 3);

        context.execute();
        assert_eq!(*observed_records.borrow(), vec![(2.5, 6)]);
    }

    #[test]
    fn schedule_relative_accepts_closure_action() {
        let mut context = Context::new();
        let records = Rc::new(RefCell::new(Vec::new()));
        let observed_records = records.clone();

        schedule_relative!(
            &mut context,
            1.25,
            |context: &mut Context, records: Rc<RefCell<Vec<(f64, u32)>>>, value: u32| {
                records
                    .borrow_mut()
                    .push((context.get_current_time(), value));
            },
            records,
            42
        );

        context.execute();
        assert_eq!(*observed_records.borrow(), vec![(1.25, 42)]);
    }

    #[test]
    fn schedule_relative_accepts_context_expression_and_no_action_arguments() {
        let mut context = Context::new();
        let records = Rc::new(RefCell::new(Vec::new()));
        let observed_records = records.clone();

        schedule_relative!(
            passthrough_context(&mut context),
            0.75,
            record_current_time,
            records
        );
        schedule_relative!(passthrough_context(&mut context), 1.5, Context::shutdown);

        context.execute();
        assert_eq!(*observed_records.borrow(), vec![0.75]);
    }
}
