name: Cargo Build & Test

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('Cargo.toml') }}
      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --verbose
      - name: Build Wasm
        run: cargo build --verbose --target wasm32-unknown-unknown --no-default-features --features logging
      - name: Build benchmarks
        run: cargo bench -p ixa-bench --no-run
      - name: Run tests
        run: cargo test --workspace --verbose
      - name: Run examples
        run: cargo test --examples
