name: Cargo Build

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Dev Build
      - run: mise run build

      - name: WASM Build
      - run: mise run build --target wasm32-unknown-unknown --release
