name: Cargo Build

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cargo-bins/cargo-binstall@v1.15.6
      - uses: jdx/mise-action@v2

      - name: Dev Build
      - run: mise run build

      - name: WASM Build
      - run: mise run build --target wasm32-unknown-unknown --release
