name: Build Docs

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo doc --no-deps
    - uses: actions/checkout@v4
      ref: gh-pages
    - name: Clean directory
      run: rm -rf docs/api
    - name: Copy docs
      run: cp -pR target/doc docs/api
 