name: Run examples

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      uses: actions/cache@v4
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ixa-12345
        path: .
