name: Run examples

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo target directory
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-target-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ runner.os }}-

      - name: Build
        run: cargo build --verbose

  run_examples:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [ basic-infection, births-deaths, load-people, network-hhmodel, parameter-loading, random, reports, reports-multi-threaded, runner, time-varying-infection ]
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo target directory
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-target-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ runner.os }}-

      - name: Run the example
        run: cargo run --example ${{ matrix.example }}
