name: Run examples

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-deps-${{ runner.os }}-

      - name: Cache Cargo target directory
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-target-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ runner.os }}-

      - name: Build
        run: cargo build --verbose

      - name: Save Cargo dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-deps-${{ runner.os }}-

      - name: Save Cargo target directory cache
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-target-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ runner.os }}-

  run_examples:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - example: basic-infection
          - example: births-deaths
          - example: load-people
          - example: network-hhmodel
          - example: parameter-loading
          - example: random
          - example: reports
          - example: reports-multi-threaded
          - example: runner
          - example: time-varying-infection
            args: ./examples/time-varying-infection/input.json
    steps:
      - uses: actions/checkout@v4

      - name: Restore Cargo dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-deps-${{ runner.os }}-

      - name: Restore Cargo target directory cache
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-target-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ runner.os }}-

      - name: Reset timestamps
        run: find target -type f -exec touch {} +

      - name: Run the example
        run: cargo run --example ${{ matrix.example }} ${{ matrix.args }}
